[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"

# Static site configuration for better compatibility
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Enable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs" 