[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"

# Next.js specific redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Enable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs" 