services:
  - type: web
    name: ignite
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: ignite-main
    plan: starter 