export const DNA_SECTIONS = [
  {
    id: "authorBiography",
    title: "1. Author Biography",
    description: "Fill in below with basic information about you, your company, and at least 3 main achievements related to your work (number of clients, TV appearances, awards, etc.).",
    placeholder: "Fill in below with basic information about you, your company, and at least 3 main achievements related to your work (number of clients, TV appearances, awards, etc.).",
    defaultValue: "i run a company called dopamine digital, thats an agency",
    maxLength: 3000,
  },
  {
    id: "idealClientProfile",
    title: "2. Ideal Client Profile",
    description: "Here is where you describe your ideal customer in detail. This information will feed almost all the agents. Remember to first use the High-Value Customer Compass to find better customers for your business... and then understand them better using the Ideal Customer Profile agent.",
    placeholder: "Paste the result of the Ideal Customer Profile here and complement if necessary.",
    defaultValue: "b2b saas founder doing 1-5million per year.",
    agents: ["High-Value Client Compass", "Ideal Client Profile (ICP)"],
    maxLength: 10000,
  },
  {
    id: "authorBrandVoice",
    title: "3. Author/Brand Voice",
    description: "Here you can paste examples and excerpts from texts, emails, sales letters, and others that you've written... OR... even the transcription of some excerpts from your videos. This way, we can \"clone your voice\" to use in agents that have this functionality. Tip: Ask an AI to analyze your text/transcription and create a \"summary of the author's communication style\" and paste it here as well.",
    defaultValue: "witty, intelligent and straight to the point",
    maxLength: 2500,
  },
  {
    id: "buyingProfile",
    title: "4. Buying Profile",
    description: "Now let's dive deeper and understand which profile or archetype your customer typically uses when making a purchase. This will be used in agents focused on marketing, copy, and sales.",
    defaultValue: "buyer is b2b saas founders who feel stuck in founder led sales and want to get their time back so they can work on the business instead of in the business.",
    agent: "Buying Profiles",
    maxLength: 5000,
  },
  {
    id: "persuasivePremise",
    title: "5. The Persuasive Premise",
    description: "This is the basic premise that will guide your entire marketing campaign. It is the target that all our communication should aim at, while also replacing wrong beliefs with better ones that help us sell.",
    note: "Paste only the first part of the agent's result, the Persuasive Premise itself. The Primary and Secondary Beliefs will go in the next agent (False Beliefs).",
    agent: "The Persuasive Premise (1st Part)",
    defaultValue: "They are stuck in a swamp-like position where they don't have enough money to hire people in-house, but they don't have enough people in-house to be able to scale the business to make more money.",
    maxLength: 3000,
  },
  {
    id: "falseBeliefs",
    title: "6. False beliefs",
    description: "Between you and a completed sale, there are false beliefs that your prospect has about your product or service. Until you address them, the sale won't happen. Therefore, we will publish strategic content that deals with these beliefs before they become a problem.",
    note: "here you paste the second part of the agent, specifically about False Beliefs.",
    agent: "Primary and Secondary Beliefs of Persuasive Premise (2nd and 3rd Parts)",
    defaultValue: "they believe cold email doesnt work",
    maxLength: 5000,
  },
  {
    id: "productOfferUVP",
    title: "7. Product Offer and UVP (Unique Value Proposition)",
    description: "Describe your offer, product, and Unique Selling Proposition (USP) in detail. This way, we can understand what you're offering and what makes it unique.",
    placeholder: "Paste the results from the Irresistible Offer, Unforgettable Offer Names, and Unique Selling Proposition agents here and complement if necessary.",
    defaultValue: "We partner with you to be a growth partner instead of an agency where we come in, fix the whole pipeline, and give you a solution to one part of the process.",
    agents: ["Irresistible Offer", "Unforgettable Offer Names", "Unique Selling Proposition"],
    maxLength: 10000,
  },
  {
    id: "proofs",
    title: "8. Proofs",
    description: "Enter here all the proofs you have about what you do, sell, and promise. The best proofs are those that only you have. Examples: awards, certifications, number of clients, achievements, revenue, celebrities, media appearances, indexes, NPS score, followers on social media, reach, views, reviews, etc.",
    note: "testimonials will come in the next section, \"9. Testimonials.\"",
    defaultValue: "Have worked with multiple SaaS companies generating more than $7M in revenue",
    maxLength: 3000,
  },
  {
    id: "testimonials",
    title: "9. Testimonials",
    description: "Here is the space for you to paste your 3 to 5 best testimonials in a summarized manner. Try to extract only the key points of each one to paste below.",
    structure: "- Testimonial Name:\n- Result:\n- Emotional Transcription:",
    note: "The best testimonials are those from people similar to your avatar (background, starting situation, challenges, etc.), who had a \"Hero's Journey\" going from the worst possible \"before\" to the best possible \"after.\" Extreme cases create the best effect: \"Wow... they can do it, so can I!\"",
    defaultValue: "Jordan was fantastic. I can't recommend him enough. Jordan is the best marketer we've worked with. If I could give Jordan 7 stars, I would.",
    maxLength: 5000,
  },
  {
    id: "theProblem",
    title: "10. The problem",
    description: "Explain what exact problem your solution solves, and if possible, fit it within the D.O.R.E.S. criteria from the [Problem & Promise] agent. Try to focus on one main problem. If you're using this for high-level ad copy, give the problem a name (Molding) and make it unique using the Main Surprising Cause agent.",
    placeholder: "Paste the results from the Problem & Promise and Main Surprising Cause agents here and complement if necessary.",
    defaultValue: "Founders don't have time to handle lead generation and sales and marketing because they have so many other things that they're focused on in the business.",
    agents: ["Problem & Promise", "Main Surprising Cause"],
    maxLength: 5000,
  },
  {
    id: "theSolution",
    title: "11. The solution",
    description: "Make it clear what your solution is, your promise, and how your prospect's life will improve after that. Remember to focus on the final destination, not the journey to get there (sell Paris as the destination, not the flight as the means). Use the agent of [Unique Primary Solution] to transform what you do into something more robust (remember: personality).",
    placeholder: "Define the promise you make to your prospect and the name of your Unique Primary Solution that will set you apart from the competition.",
    agents: ["Problem & Promise", "Unique Primary Solution"],
    defaultValue: "",
    maxLength: 5000,
  },
];

